version: 2.1

orbs:
    node: circleci/node@1.1.6

jobs:
    test:
        docker:
            - image: circleci/node:14
        steps:
            - checkout
            - run: npm install
            - run: npm test
    build-and-push:
        docker:
            - image: circleci/node:14
        steps:
            - checkout
            - setup_remote_docker:
                  version: 20.10.7
            - run:
                  name: Build Docker image
                  command: docker build -t express-circleci:latest .
            - run:
                  name: Docker Login
                  command: |
                      echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            - run:
                  name: Tag Docker image
                  command: docker tag express-circleci:latest $DOCKERHUB_USERNAME/express-circleci:latest
            - run:
                  name: Push Docker image
                  command: docker push $DOCKERHUB_USERNAME/express-circleci:latest
workflows:
    my-pipeline:
        jobs:
            - test
            - build-and-push:
                  requires:
                      - test
